#!/bin/bash

let FNUMBER=110
let FOCALLEN=100
let ABERRATION=0

FSTOPS=( 30 40 56 80 110 160 220 320 440 )
FLENS=( 16 50 100 200 300 )

VALUES=(
    0.102	0.105	0.11	0.13	0.14	0.14	0.13	"x"	"x"
    "x"	"x"	"x"	0.05	0.055	0.06	0.07	0.08	"x"
    "x"	"x"	"x"	0.045	0.048	0.05	0.06	0.062	0.062
    "x"	"x"	0.24	0.17	0.16	0.16	0.16	0.16	0.16
    "x"	"x"	0.27	0.23	0.2	0.205	0.21	0.217	0.215
)

let INDEX=0

for l in ${FLENS[@]}; do

    for f in ${FSTOPS[@]}; do

        if (( l >= FOCALLEN )); then

            if (( f >= FNUMBER )); then

                echo $l, $f
                echo ${INDEX}
                echo ${VALUES[$INDEX]}
                break 2
            fi    
        fi    

        ((INDEX++))

    done

done
